import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Footer } from '@/components/Footer'

export const metadata = {
  title: 'Privacy Policy - Repvion',
  description: 'Repvion Privacy Policy. How we collect and use your data.',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/">
            <h1 className="text-2xl font-bold">Repvion</h1>
          </Link>
          <Link href="/">
            <Button variant="ghost">Back to Home</Button>
          </Link>
        </div>
      </header>

      <main className="flex-1 container mx-auto px-4 py-8 max-w-3xl">
        <h2 className="text-3xl font-bold mb-6">Privacy Policy</h2>
        <p className="text-sm text-muted-foreground mb-8">Last updated: March 2025</p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6 text-muted-foreground">
          <section>
            <h3 className="text-lg font-semibold text-foreground">1. Introduction</h3>
            <p>
              Repvion (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) respects your privacy. This Privacy Policy explains what
              information we collect, how we use it, and your choices. By using our service, you agree to this policy.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">2. Information We Collect</h3>
            <p className="mb-2">We collect information you provide and data generated by your use of the service:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong className="text-foreground">Account data:</strong> email address, username, and password (stored securely).</li>
              <li><strong className="text-foreground">Profile data:</strong> age, height, weight, experience level, goals, and equipment preferences you enter.</li>
              <li><strong className="text-foreground">Workout data:</strong> plans, completed workouts, sets, reps, and weights you log.</li>
              <li><strong className="text-foreground">Progress data:</strong> XP, levels, streaks, and reward unlocks.</li>
              <li><strong className="text-foreground">Social data:</strong> who you follow and your presence on leaderboards.</li>
              <li><strong className="text-foreground">Technical data:</strong> session information (e.g., via cookies or similar tech) necessary for authentication and security.</li>
            </ul>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">3. How We Use Your Information</h3>
            <p>We use your information to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Provide, maintain, and improve the service (e.g., generating plans, tracking progress, leaderboards).</li>
              <li>Authenticate your account and protect against abuse.</li>
              <li>Send you service-related communications (e.g., password reset) where applicable.</li>
              <li>Comply with legal obligations and enforce our Terms of Service.</li>
            </ul>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">4. Sharing & Disclosure</h3>
            <p>
              We do not sell your personal information. We may share data: (1) with service providers who assist in
              operating the service (e.g., hosting, analytics) under strict confidentiality; (2) if required by law or
              to protect rights and safety; (3) in connection with a merger or sale of assets, with notice as required
              by law. Profile and leaderboard information may be visible to other users as part of the social features
              you use.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">5. Data Retention & Security</h3>
            <p>
              We retain your data for as long as your account is active or as needed to provide the service and comply
              with law. We use reasonable technical and organizational measures to protect your data; no system is
              completely secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">6. Your Rights</h3>
            <p>
              Depending on your location, you may have rights to access, correct, delete, or export your data, or to
              object to or restrict certain processing. You can update profile and account details in Settings. To
              exercise other rights or delete your account, contact us. We will respond in accordance with applicable
              law (e.g., GDPR, CCPA).
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">7. Children</h3>
            <p>
              The service is not directed at children under 13. We do not knowingly collect personal information from
              children under 13. If you believe we have collected such information, please contact us so we can delete
              it.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">8. Changes</h3>
            <p>
              We may update this Privacy Policy from time to time. We will post the updated policy and, where required
              by law, notify you of material changes. Your continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-foreground">9. Contact</h3>
            <p>
              For privacy-related questions or requests, please contact us through the contact information provided on
              our website or in the app.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}
